name: Pull Request

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Generate types (PandaCSS + React Router)
              run: pnpm run setup

            - name: Type Check
              run: pnpm tsc -b

            - name: Lint
              run: pnpm nx run-many --target=lint --all

            - name: Build
              run: pnpm nx build website
